# Browser configuration constants
BROWSER_ARGS = [
    "--no-first-run",
    "--no-default-browser-check",
    "--disable-blink-features=AutomationControlled",
    "--disable-features=VizDisplayCompositor",
    "--disable-ipc-flooding-protection",
    "--disable-renderer-backgrounding",
    "--disable-backgrounding-occluded-windows",
    "--disable-features=TranslateUI",
    "--disable-features=BlinkGenPropertyTrees",
    "--no-sandbox",
    "--disable-setuid-sandbox",
    "--disable-dev-shm-usage",
    "--disable-accelerated-2d-canvas",
    "--disable-accelerated-jpeg-decoding",
    "--disable-accelerated-mjpeg-decode",
    "--disable-accelerated-video-decode",
    "--disable-accelerated-video-encode",
    "--disable-app-list-dismiss-on-blur",
    "--disable-background-timer-throttling",
    "--disable-backgrounding-occluded-windows",
    "--disable-renderer-backgrounding",
    "--disable-features=TranslateUI",
    "--disable-extensions",
    "--disable-plugins",
    "--disable-default-apps",
    "--disable-hang-monitor",
    "--disable-prompt-on-repost",
    "--disable-sync",
    "--disable-web-security",
    "--metrics-recording-only",
    "--safebrowsing-disable-auto-update",
    "--enable-automation=false",
    "--password-store=basic",
    "--use-mock-keychain",
]


CONTEXT_CONFIG = {
    "viewport": {"width": 1366, "height": 768},
    "locale": "en-US",
    "timezone_id": "America/New_York",
    "permissions": ["geolocation"],
    "geolocation": {"longitude": -74.006, "latitude": 40.7128},
    "color_scheme": "light",
    "extra_http_headers": {
        "Accept-Language": "en-US,en;q=0.9",
        "Accept-Encoding": "gzip, deflate, br",
        "Upgrade-Insecure-Requests": "1",
        "Sec-Fetch-Site": "none",
        "Sec-Fetch-Mode": "navigate",
        "Sec-Fetch-User": "?1",
        "Sec-Fetch-Dest": "document",
    },
}

IGNORE_DEFAULT_ARGS = [
    "--enable-automation",
    "--use-mock-keychain",
    "--password-store=basic",
]
